name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
	with:
          username: ${{ secrets.raghulspnair }}
          password: ${{ secrets.Raghul@2702 }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                      
          file: ./Dockerfile              
          push: true                      
          tags: raghulspnair/go-app:latest  

 
